### ISSUE TITLE
Problem encountered while install rocketchat-otrs

### ISSUE THREAD

**Issue by PaulYangsmile** [ndom91/rocketchat-otrs#1]
We tried to install the apps under rocketchat.

Finally in the last step: rc-apps deploy, the following error message come to us:

Starting App Deployment to Server
   Getting Server Info... ✓
   Packaging the app... ✖
 ›   Error:    ⟿  Error 
 ›   /root/rocketchat-otrs/node_modules/@types/node/events.d.ts (20,60): Cannot 
 ›   find name 'AsyncIterableIterator'.

Please kindly help to make some comments on the problem.

Thank you very much in advance!
Paul

**Comment by ndom91** [comment]
Hmm what version of node do you have installed there?

**Comment by yederlv** [comment]
Hello, I'm trying to deploy the application but I have following error

```
rc-apps deploy --url http://127.0.0.1 --username testrocket --password test
   Starting App Deployment to Server

   Getting Server Info... ✓
   Packaging the app... ✖
 »   Error:    ⟿  TicketPoster_1.TicketPoster is not a constructor
```
I am using the following versions:
Rocketchat 5.0.3
NodeJs 16.15.1
npm 8.19.1

Thank You

**Comment by ndom91** [comment]
This was only tested with the latest version of RocketChat ~Dec 2020, i.e. `~3.7`.

Unfortunately I don't have a RocketChat instance to continue to test this with.
